name: BUILD

on:
  # push on master branch
  push:
    branches: [master]
  # triggered manually
  workflow_dispatch:
  # triggered by pull requests
  pull_request:

jobs:
  compile:
    runs-on: ubuntu-latest
#    container: pandoc/extra:latest-ubuntu
    steps:
      - uses: actions/checkout@v4
      - run: make eisvogel
